# Generated by Django 5.1 on 2024-09-23 14:05

import django.db.models.deletion
import liveresults.apps.teams.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0002_rename_leauges_lea_name_51e5fa_idx_leagues_lea_name_1b3d9e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='images/teams/logos/', validators=[liveresults.apps.teams.validators.validate_png])),
                ('city', models.CharField(max_length=128)),
                ('stadium', models.CharField(blank=True, max_length=128)),
                ('established_date', models.DateField(blank=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='leagues.league')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(allow_unicode=True, blank=True)),
                ('year', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], default='Domestic', max_length=13)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honors', to='teams.team')),
            ],
            options={
                'verbose_name': 'honor',
                'verbose_name_plural': 'honors',
                'ordering': ['year'],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='teams_team_name_43e047_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['city'], name='teams_team_city_493421_idx'),
        ),
        migrations.AddIndex(
            model_name='honor',
            index=models.Index(fields=['title'], name='teams_honor_title_40c2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='honor',
            index=models.Index(fields=['year'], name='teams_honor_year_cb5bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='honor',
            index=models.Index(fields=['level'], name='teams_honor_level_3fa5c9_idx'),
        ),
    ]
