# Generated by Django 5.1 on 2024-09-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
